@extends('admin.layouts.app')
@section('title', 'Sales & Operation Referral Leads')

@section('header-css')
<style>
    .arl-wrapper { background: #f5f7fb; }
    .arl-card {
        border: 0;
        border-radius: 14px;
        box-shadow: 0 8px 24px rgba(15, 23, 42, 0.06);
        overflow: hidden;
    }
    .arl-header {
        background: linear-gradient(180deg, #fff 0%, #fff8f1 100%);
        border-bottom: 1px solid #fee2c8;
        padding: 1rem 1.15rem;
    }
    .arl-stats { display: flex; flex-wrap: wrap; gap: 0.5rem; margin-bottom: 0.85rem; }
    .arl-pill {
        display: inline-flex;
        align-items: center;
        gap: 0.35rem;
        font-size: 0.78rem;
        font-weight: 700;
        padding: 0.35rem 0.7rem;
        border-radius: 999px;
        border: 1px solid #e5e7eb;
        background: #fff;
        color: #475569;
        text-decoration: none;
    }
    .arl-pill:hover { text-decoration: none; color: #0f172a; border-color: #fdba74; }
    .arl-pill.active { background: #fff7ed; color: #9a3412; border-color: #fed7aa; }
    .arl-table thead th {
        font-size: 0.72rem;
        text-transform: uppercase;
        letter-spacing: 0.04em;
        color: #9a3412;
        background: #fff7ed;
        border-bottom: 2px solid #fed7aa !important;
        white-space: nowrap;
    }
    .arl-table tbody td { vertical-align: middle; color: #334155; font-size: 0.88rem; }
    .arl-detail { max-width: 200px; white-space: pre-wrap; word-break: break-word; }
    .arl-row-rejected { background: #fff1f2 !important; }
    .arl-row-pending { background: #fffbeb !important; }
    .arl-badge {
        display: inline-block;
        font-size: 0.72rem;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 0.03em;
        padding: 0.22rem 0.5rem;
        border-radius: 999px;
    }
    .arl-badge-pending { background: #fffbeb; color: #b45309; border: 1px solid #fde68a; }
    .arl-badge-approved { background: #ecfdf5; color: #047857; border: 1px solid #a7f3d0; }
    .arl-badge-rejected { background: #fef2f2; color: #b91c1c; border: 1px solid #fecaca; }
</style>
@endsection

@section('main')
@php
    $userName = function ($u) {
        if (! $u) return '—';
        $n = trim(($u->f_name ?? '').' '.($u->l_name ?? ''));
        return $n !== '' ? $n : '—';
    };
    $commissionUsers = $commissionUsers ?? collect();
@endphp
<div class="content-wrapper arl-wrapper">
    <section class="content">
        <div class="container-fluid pt-3">
            <div class="card arl-card">
                <div class="card-header arl-header d-flex align-items-center justify-content-between flex-wrap">
                    <div>
                        <h3 class="card-title mb-0">
                            <i class="fas fa-share-square mr-2" style="color:#F07F28"></i>
                            Sales &amp; Operation Referral Leads
                        </h3>
                        <p class="text-muted small mb-0 mt-1">
                            All referral leads generated by sales / operation users — manager response and commission.
                        </p>
                    </div>
                    <button type="button" class="btn btn-sm btn-outline-warning text-nowrap mt-2 mt-md-0" data-bs-toggle="modal" data-bs-target="#setReferralLeadCommissionModal">
                        <i class="fas fa-percent mr-1"></i>Set commission %
                    </button>
                </div>
                <div class="card-body">
                    <div class="arl-stats">
                        <a href="{{ route('admin.referral_leads.index') }}" class="arl-pill {{ $status === '' ? 'active' : '' }}">All <span>{{ $counts['all'] }}</span></a>
                        <a href="{{ route('admin.referral_leads.index', ['status' => 'pending']) }}" class="arl-pill {{ $status === 'pending' ? 'active' : '' }}">Pending <span>{{ $counts['pending'] }}</span></a>
                        <a href="{{ route('admin.referral_leads.index', ['status' => 'approved']) }}" class="arl-pill {{ $status === 'approved' ? 'active' : '' }}">Approved <span>{{ $counts['approved'] }}</span></a>
                        <a href="{{ route('admin.referral_leads.index', ['status' => 'rejected']) }}" class="arl-pill {{ $status === 'rejected' ? 'active' : '' }}">Rejected <span>{{ $counts['rejected'] }}</span></a>
                    </div>

                    <div class="table-responsive">
                        <table class="table arl-table mb-0">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Source</th>
                                    <th>Generated by</th>
                                    <th>Number</th>
                                    <th>Service</th>
                                    <th>Detail</th>
                                    <th>Bulk</th>
                                    <th>Commission %</th>
                                    <th>Manager</th>
                                    <th>Manager response</th>
                                    <th>Assigned to</th>
                                    <th>Reviewed</th>
                                    <th>Generated at</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($items as $item)
                                    @php
                                        $st = $item->status ?? 'pending';
                                        $rowClass = $st === 'rejected' ? 'arl-row-rejected' : ($st === 'pending' ? 'arl-row-pending' : '');
                                    @endphp
                                    <tr class="{{ $rowClass }}">
                                        <td>{{ $item->id }}</td>
                                        <td>
                                            @if(($item->source ?? 'sales') === 'operation')
                                                <span class="badge badge-info">Operation</span>
                                            @else
                                                <span class="badge badge-primary">Sales</span>
                                            @endif
                                        </td>
                                        <td class="font-weight-bold">{{ $userName($item->generatedBy) }}</td>
                                        <td>{{ $item->mobile }}</td>
                                        <td>{{ $item->service ?: '—' }}</td>
                                        <td class="arl-detail">{{ $item->detail ?: '—' }}</td>
                                        <td>{{ $item->bulk_qty }}</td>
                                        <td class="text-nowrap">{{ $item->commission_percent !== null ? number_format((float) $item->commission_percent, 2).'%' : '—' }}</td>
                                        <td>{{ $userName($item->manager) }}</td>
                                        <td>
                                            @if($st === 'approved')
                                                <span class="arl-badge arl-badge-approved">Approved</span>
                                            @elseif($st === 'rejected')
                                                <span class="arl-badge arl-badge-rejected">Rejected</span>
                                            @else
                                                <span class="arl-badge arl-badge-pending">Pending</span>
                                            @endif
                                            @if(in_array($st, ['approved', 'rejected'], true) && $item->reviewed_at)
                                                <div class="small text-muted mt-1">{{ $item->reviewed_at->format('d M Y, h:i A') }}</div>
                                            @endif
                                            @if($item->manager_remark)
                                                <div class="small text-muted mt-1">{{ $item->manager_remark }}</div>
                                            @endif
                                        </td>
                                        <td>{{ $userName($item->assignedExecutive) }}</td>
                                        <td class="small text-nowrap">
                                            @if($item->reviewed_at)
                                                {{ $userName($item->reviewedBy) }}
                                                <div class="text-muted">{{ $item->reviewed_at->format('d M Y, H:i') }}</div>
                                            @else
                                                —
                                            @endif
                                        </td>
                                        <td class="text-nowrap small">{{ $item->created_at?->format('d M Y, H:i') ?? '—' }}</td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="13" class="text-center text-muted py-4">
                                            <i class="fas fa-inbox mr-1"></i>No referral leads found.
                                        </td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>

                    @if($items->hasPages())
                        <div class="mt-3">{{ $items->links() }}</div>
                    @endif
                </div>
            </div>
        </div>
    </section>
</div>

<div class="modal fade" id="setReferralLeadCommissionModal" tabindex="-1" aria-labelledby="setReferralLeadCommissionModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="setReferralLeadCommissionModalLabel">
                    <i class="fas fa-percent text-warning mr-2"></i>Set referral lead commission
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="POST" action="{{ route('admin.referral_leads.commission') }}" id="referralLeadCommissionForm">
                @csrf
                <div class="modal-body">
                    <p class="small text-muted mb-3">
                        Commission for leads generated from <strong>Sales / Operation → Referral Leads</strong>.
                        Default is <strong>10%</strong> per lead. Select users and set a percentage (can differ per user by saving again).
                    </p>
                    <div class="form-group">
                        <label class="font-weight-bold">Commission % <span class="text-danger">*</span></label>
                        <input type="number" name="commission_percent" class="form-control" min="0" max="100" step="0.01" value="10" required placeholder="e.g. 10">
                        <small class="text-muted">Applied to all selected users below.</small>
                    </div>
                    <div class="d-flex align-items-center justify-content-between flex-wrap mb-2">
                        <label class="font-weight-bold mb-0">Sales &amp; Operation users</label>
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="referralLeadCommissionSelectAll">
                            <label class="custom-control-label" for="referralLeadCommissionSelectAll">Select all visible</label>
                        </div>
                    </div>
                    <div class="d-flex flex-wrap align-items-center mb-2" style="gap:0.4rem;">
                        <div class="btn-group btn-group-sm" role="group" aria-label="Role filter">
                            <button type="button" class="btn btn-outline-secondary arl-comm-role-filter active" data-role="">All</button>
                            <button type="button" class="btn btn-outline-primary arl-comm-role-filter" data-role="sales">Sales</button>
                            <button type="button" class="btn btn-outline-info arl-comm-role-filter" data-role="operation">Operation</button>
                        </div>
                        <div class="flex-grow-1" style="min-width:180px;">
                            <input type="search" id="referralLeadCommissionSearch" class="form-control form-control-sm" placeholder="Search name or mobile…" autocomplete="off">
                        </div>
                    </div>
                    @if($commissionUsers->isEmpty())
                        <p class="text-muted mb-0">No active Sales or Operation users found.</p>
                    @else
                        <div class="border rounded" style="max-height: 320px; overflow-y: auto;">
                            <table class="table table-sm table-hover mb-0" id="referralLeadCommissionTable">
                                <thead class="thead-light" style="position: sticky; top: 0; z-index: 1;">
                                    <tr>
                                        <th style="width:42px;"></th>
                                        <th>User</th>
                                        <th>Role</th>
                                        <th>Mobile</th>
                                        <th class="text-right">Current %</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($commissionUsers as $cu)
                                        @php
                                            $currentPct = $cu->referral_lead_commission_percent !== null
                                                ? (float) $cu->referral_lead_commission_percent
                                                : 10.0;
                                            $roleIds = array_map('trim', explode(',', (string) $cu->role_id));
                                            $roleKey = in_array('2', $roleIds, true) ? 'sales' : 'operation';
                                            $roleLabel = $roleKey === 'sales' ? 'Sales' : 'Operation';
                                            $cuName = trim(($cu->f_name ?? '').' '.($cu->l_name ?? ''));
                                            $displayName = $cuName !== '' ? $cuName : 'User #'.$cu->id;
                                            $searchText = strtolower($displayName.' '.($cu->mobile ?? ''));
                                        @endphp
                                        <tr class="arl-comm-user-row" data-role="{{ $roleKey }}" data-search="{{ e($searchText) }}">
                                            <td>
                                                <input type="checkbox" class="referral-lead-user-check" name="user_ids[]" value="{{ $cu->id }}">
                                            </td>
                                            <td class="font-weight-600">{{ $displayName }}</td>
                                            <td>
                                                @if($roleKey === 'sales')
                                                    <span class="badge badge-primary">Sales</span>
                                                @else
                                                    <span class="badge badge-info">Operation</span>
                                                @endif
                                            </td>
                                            <td class="text-nowrap">{{ $cu->mobile ?: '—' }}</td>
                                            <td class="text-right text-nowrap">{{ number_format($currentPct, 2) }}%</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <p id="referralLeadCommissionEmptyFilter" class="text-muted small mb-0 mt-2 d-none">No users match this filter / search.</p>
                        <small class="text-muted d-block mt-2"><span id="referralLeadCommissionSelectedCount">0</span> user(s) selected · <span id="referralLeadCommissionVisibleCount">{{ $commissionUsers->count() }}</span> shown</small>
                    @endif
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-warning text-dark font-weight-bold" id="referralLeadCommissionSaveBtn" {{ $commissionUsers->isEmpty() ? 'disabled' : '' }}>
                        Save commission
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('footer-script')
<script>
$(function() {
    var roleFilter = '';

    function visibleRows() {
        return $('.arl-comm-user-row:visible');
    }

    function updateReferralLeadCommissionCount() {
        var $visible = visibleRows();
        var n = $visible.find('.referral-lead-user-check:checked').length;
        var totalVisible = $visible.length;
        $('#referralLeadCommissionSelectedCount').text($('.referral-lead-user-check:checked').length);
        $('#referralLeadCommissionVisibleCount').text(totalVisible);
        var selectAll = $('#referralLeadCommissionSelectAll');
        if (totalVisible) {
            selectAll.prop('checked', n === totalVisible);
            selectAll.prop('indeterminate', n > 0 && n < totalVisible);
        } else {
            selectAll.prop('checked', false).prop('indeterminate', false);
        }
        $('#referralLeadCommissionEmptyFilter').toggleClass('d-none', totalVisible > 0 || !$('.arl-comm-user-row').length);
    }

    function applyCommissionUserFilters() {
        var q = ($('#referralLeadCommissionSearch').val() || '').toString().trim().toLowerCase();
        var visible = 0;
        $('.arl-comm-user-row').each(function() {
            var $row = $(this);
            var roleOk = !roleFilter || $row.data('role') === roleFilter;
            var searchOk = !q || String($row.data('search') || '').indexOf(q) !== -1;
            var show = roleOk && searchOk;
            $row.toggle(show);
            if (show) visible++;
        });
        updateReferralLeadCommissionCount();
    }

    $('.arl-comm-role-filter').on('click', function() {
        $('.arl-comm-role-filter').removeClass('active');
        $(this).addClass('active');
        roleFilter = ($(this).data('role') || '').toString();
        applyCommissionUserFilters();
    });

    $('#referralLeadCommissionSearch').on('input', applyCommissionUserFilters);

    $('#referralLeadCommissionSelectAll').on('change', function() {
        visibleRows().find('.referral-lead-user-check').prop('checked', this.checked);
        updateReferralLeadCommissionCount();
    });

    $(document).on('change', '.referral-lead-user-check', updateReferralLeadCommissionCount);

    $('#referralLeadCommissionForm').on('submit', function(e) {
        // Only submit currently visible selected users (filter / search respect)
        $('.arl-comm-user-row:hidden .referral-lead-user-check').prop('disabled', true);
        if ($('.arl-comm-user-row:visible .referral-lead-user-check:checked').length < 1) {
            e.preventDefault();
            $('.arl-comm-user-row:hidden .referral-lead-user-check').prop('disabled', false);
            alert('Please select at least one visible user.');
            return false;
        }
    });

    $('#setReferralLeadCommissionModal').on('hidden.bs.modal', function() {
        $('.arl-comm-user-row:hidden .referral-lead-user-check').prop('disabled', false);
    });
});
</script>
@endsection
