@extends('operation_manager.layouts.app')
@section('title', 'Referral Leads')

@section('header-css')
<style>
    .mrl-wrapper { background: #f5f7fb; min-height: calc(100vh - 120px); }
    .mrl-card {
        border: 0;
        border-radius: 14px;
        box-shadow: 0 8px 24px rgba(15, 23, 42, 0.06);
        overflow: hidden;
    }
    .mrl-header {
        background: linear-gradient(180deg, #fff 0%, #fff8f1 100%);
        border-bottom: 1px solid #fee2c8;
        padding: 1rem 1.15rem;
    }
    .mrl-table thead th {
        font-size: 0.75rem;
        text-transform: uppercase;
        letter-spacing: 0.04em;
        color: #9a3412;
        background: #fff7ed;
        border-bottom: 2px solid #fed7aa !important;
        white-space: nowrap;
    }
    .mrl-table tbody td { vertical-align: middle; color: #334155; font-size: 0.9rem; }
    .mrl-detail { max-width: 220px; white-space: pre-wrap; word-break: break-word; }
    .mrl-row-rejected { background: #fff1f2 !important; }
    .mrl-badge {
        display: inline-block;
        font-size: 0.72rem;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 0.03em;
        padding: 0.22rem 0.5rem;
        border-radius: 999px;
    }
    .mrl-badge-pending { background: #fffbeb; color: #b45309; border: 1px solid #fde68a; }
    .mrl-badge-approved { background: #ecfdf5; color: #047857; border: 1px solid #a7f3d0; }
    .mrl-badge-rejected { background: #fef2f2; color: #b91c1c; border: 1px solid #fecaca; }
</style>
@endsection

@section('main')
<div class="content-wrapper mrl-wrapper">
    <section class="content">
        <div class="container-fluid pt-3">
            <div class="card mrl-card">
                <div class="card-header mrl-header">
                    <h3 class="card-title mb-0"><i class="fas fa-share-square mr-2" style="color:#F07F28"></i>Referral Leads</h3>
                    <p class="text-muted small mb-0 mt-1">Leads generated by your operation team. Approve to assign to a sales executive, or reject.</p>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table mrl-table mb-0">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Generated by</th>
                                    <th>Number</th>
                                    <th>Service</th>
                                    <th>Detail</th>
                                    <th>Bulk</th>
                                    <th>Status</th>
                                    <th>Assigned to</th>
                                    <th>Submitted</th>
                                    <th class="text-center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($items as $item)
                                    <tr class="{{ $item->isRejected() ? 'mrl-row-rejected' : '' }}">
                                        <td>{{ $item->id }}</td>
                                        <td>
                                            @if($item->generatedBy)
                                                {{ trim(($item->generatedBy->f_name ?? '').' '.($item->generatedBy->l_name ?? '')) ?: '—' }}
                                            @else
                                                —
                                            @endif
                                        </td>
                                        <td class="font-weight-bold">{{ $item->mobile }}</td>
                                        <td>{{ $item->service ?: '—' }}</td>
                                        <td class="mrl-detail">{{ $item->detail ?: '—' }}</td>
                                        <td>{{ $item->bulk_qty }}</td>
                                        <td>
                                            @if($item->status === 'approved')
                                                <span class="mrl-badge mrl-badge-approved">Approved</span>
                                            @elseif($item->status === 'rejected')
                                                <span class="mrl-badge mrl-badge-rejected">Rejected</span>
                                            @else
                                                <span class="mrl-badge mrl-badge-pending">Pending</span>
                                            @endif
                                        </td>
                                        <td>
                                            @if($item->assignedExecutive)
                                                {{ trim(($item->assignedExecutive->f_name ?? '').' '.($item->assignedExecutive->l_name ?? '')) ?: '—' }}
                                            @else
                                                —
                                            @endif
                                        </td>
                                        <td class="text-nowrap small">{{ $item->created_at?->format('d M Y, H:i') ?? '—' }}</td>
                                        <td class="text-center text-nowrap">
                                            @if($item->isPending())
                                                <form method="POST" action="{{ route('operation-manager.referral_leads.approve', $item) }}" class="d-inline" onsubmit="return confirm('Approve and assign this lead to a sales executive?');">
                                                    @csrf
                                                    <button type="submit" class="btn btn-sm btn-success">Approve</button>
                                                </form>
                                                <form method="POST" action="{{ route('operation-manager.referral_leads.reject', $item) }}" class="d-inline" onsubmit="return confirm('Reject this referral lead?');">
                                                    @csrf
                                                    <button type="submit" class="btn btn-sm btn-outline-danger">Reject</button>
                                                </form>
                                            @else
                                                <span class="text-muted small">—</span>
                                            @endif
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="10" class="text-center text-muted py-4">
                                            <i class="fas fa-inbox mr-1"></i>No referral leads from your team yet.
                                        </td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection
